spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

jwt:
  secret:
    key: LLAVE_SECRETA

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/concesionario_coches
    username: ana
    password: root1234

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---

spring:

  config:
    activate:
      on-profile: prod

  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            profile:
            credential:

  datasource:
    url: ${spring-data-source-url}
    #username: ${spring-datasource-username}
    #password: ${spring-datasource-password}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



